Repository TeamChaRo/ChaRo-iOS, pull requests merged in 2021-12, with the labels that each got.

#159 ✨[FEAT] 'NEW' 마이페이지 구현
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/GoogleService-Info.plist
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/MyPageScene/MyPage.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/CommonCVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Models/MyPageDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Models/MypageInfinityDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/Contants.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/MypageInfinityService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/CommonCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/HomeScene/HomePostDetailCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/MyPageScene/MyPagePostCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/NewHotFilterView.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/MyPageScene/MyPageVC.swift
  ChaRo-iOS/Podfile
  ChaRo-iOS/Podfile.lock
Labels: enhancement, help wanted, P0, 🍉 parkikbum 😝, Refactor🔨, 마이페이지뷰

#166 상세보기 서버 연결 수정과 관련 뷰 데이터 수정 및 리펙토링
  .gitignore
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/UIView+.swift
  ChaRo-iOS/ChaRo-iOS/Source/Models/GenericResponse.swift
  ChaRo-iOS/ChaRo-iOS/Source/Models/PostDetailDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/CommonData.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/Contants.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/PostResultService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/SearchKeywordService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeScene/HomeSeasonRecommandTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostDetailScene/PostPathMapTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/ThemeScene/ThemePostAllTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Shared/Component/LeftBackButton.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/AddressMainVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeScene/HomePostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeScene/HomeVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailScene/PostDetailVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostSearchScene/SearchPostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostSearchScene/SearchResultVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/ThemeScene/ThemePostVC.swift
  ChaRo-iOS/Podfile
  ChaRo-iOS/Podfile.lock
Labels: P0, 🍑hryeong🍑, Refactor🔨, Review Required☀️, 상세보기뷰

#173 ✨[FEAT] 마이페이지 끄으으으으ㅡㅡ으ㅡㅡ읕~!
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/FollowButtonImage.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/FollowButtonImage.imageset/FollowButtonImage.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/FollowButtonImage.imageset/FollowButtonImage@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/FollowButtonImage.imageset/FollowButtonImage@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/followingButtonImage.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/followingButtonImage.imageset/followingButtonImage.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/followingButtonImage.imageset/followingButtonImage@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/followingButtonImage.imageset/followingButtonImage@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/FollowScene/FollowFollowing.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/FollowScene/FollowFollowingTVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Models/GetFollowDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/Contants.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/GetFollowDataService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/FollowScene/FollowFollowingTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/FollowScene/FollowFollwingVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/MyPageScene/MyPageVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/MyPageScene/OtherMyPageVC.swift
Labels: P0, 🍉 parkikbum 😝, 마이페이지뷰
