Repository TeamChaRo/ChaRo-iOS, pull requests merged in 2021-07, with the labels that each got.

#8 ➕[ADD] home스토리보드,home뷰컨트롤 추가 및 테이블 뷰 추가
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/Home.storyboard
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeVC.swift
Labels: P0, documentation

#2 ✅[CHORE] CollectionView, TableView, UIView extension 함수 추가
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/Extension+UICollectionView.swift
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/Extension+UITableView.swift
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/Extension+UIView.swift
  ChaRo-iOS/Podfile.lock
Labels: P1

#15 ✨[FEAT] : #14 - tabbar item 커스텀후 tabbar 연결
  .gitignore
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tabbarBackground.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tabbarBackground.imageset/rectangle62.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tabbarBackground.imageset/rectangle62@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tabbarBackground.imageset/rectangle62@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tabbarBackgroundTest.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tabbarBackgroundTest.imageset/tabbarBackgroundTest.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tabbarIcHomeActive.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tabbarIcHomeActive.imageset/tabbarIcHomeActive.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tabbarIcHomeActive.imageset/tabbarIcHomeActive@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tabbarIcHomeActive.imageset/tabbarIcHomeActive@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tabbarIcHomeInactive.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tabbarIcHomeInactive.imageset/tabbarIcHomeInactive.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tabbarIcHomeInactive.imageset/tabbarIcHomeInactive@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tabbarIcHomeInactive.imageset/tabbarIcHomeInactive@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tabbarIcMypageActive.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tabbarIcMypageActive.imageset/tabbarIcMypageActive.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tabbarIcMypageActive.imageset/tabbarIcMypageActive@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tabbarIcMypageActive.imageset/tabbarIcMypageActive@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tabbarIcMypageInactive.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tabbarIcMypageInactive.imageset/tabbarIcMypageInactive.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tabbarIcMypageInactive.imageset/tabbarIcMypageInactive@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tabbarIcMypageInactive.imageset/tabbarIcMypageInactive@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tabbarIcPostWrite.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tabbarIcPostWrite.imageset/tabbarIcWrite.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tabbarIcPostWrite.imageset/tabbarIcWrite@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tabbarIcPostWrite.imageset/tabbarIcWrite@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Info.plist
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/Base.lproj/Main.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/Tabbar.storyboard
  ChaRo-iOS/ChaRo-iOS/Source/Services/MapService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/TabbarVC.swift
Labels: P0

#20 ✨ [FEAT] HomeView - TVC, CVC 틀 구현
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icHeartWhiteLine.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icHeartWhiteLine.imageset/icHeartWhiteLine.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icHeartWhiteLine.imageset/icHeartWhiteLine@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icHeartWhiteLine.imageset/icHeartWhiteLine@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tempImageBig.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tempImageBig.imageset/image-placeholder.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tempImageBig.imageset/image-placeholder@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tempImageBig.imageset/image-placeholder@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tempImageCircle.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tempImageCircle.imageset/Rectangle 114.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tempImageCircle.imageset/Rectangle 114@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tempImageCircle.imageset/Rectangle 114@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tempImageSmall.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tempImageSmall.imageset/image-placeholder.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tempImageSmall.imageset/image-placeholder@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/tempImageSmall.imageset/image-placeholder@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/CommonCVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/HomeAnimationCVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/HomeThemeCVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/HomeAnimationTVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/HomeSquareTVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/HomeThemeTVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/HomeTodayDriveTVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/Extension+UITableView.swift
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/Extension+UITableViewCell.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/CommonCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/HomeAnimationCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/HomeThemeCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeAnimationTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeSquareTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeThemeTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeTodayDriveTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeVC.swift
Labels: P0, 🤍kingwonee🤍

#22 ✨[FEAT] : #11 - 구경하기뷰 title 영역 cell 구현
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/heart_count_no text.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/heart_count_no text.imageset/heart_count_no text.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/heart_count_no text.imageset/heart_count_no text@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/heart_count_no text.imageset/heart_count_no text@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/myimage.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/myimage.imageset/myimage.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/myimage.imageset/myimage@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/myimage.imageset/myimage@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/PostDetail.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/PostTitleTVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Models/PostTitleDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/MapService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/PostTitleTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailVC.swift
Labels: P0, 💖 InDong 💖

#24 Feature/17 make post parking and attention cells
  .gitignore
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/postAttentionSelected.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/postAttentionSelected.imageset/ui:view:selectbox_show.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/postAttentionSelected.imageset/ui:view:selectbox_show@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/postAttentionSelected.imageset/ui:view:selectbox_show@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/postAttentionUnselected.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/postAttentionUnselected.imageset/ui:view:selectbox_warning_unselect.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/postAttentionUnselected.imageset/ui:view:selectbox_warning_unselect@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/postAttentionUnselected.imageset/ui:view:selectbox_warning_unselect@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/postParkingSelected.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/postParkingSelected.imageset/ui:view:selectbox_yes@1x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/postParkingSelected.imageset/ui:view:selectbox_yes@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/postParkingSelected.imageset/ui:view:selectbox_yes@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/postParkingUnselected.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/postParkingUnselected.imageset/ui:view:selectbox_no@1x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/postParkingUnselected.imageset/ui:view:selectbox_no@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/postParkingUnselected.imageset/ui:view:selectbox_no@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/postTextFieldParkingShow.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/postTextFieldParkingShow.imageset/uiViewTextfieldParkingShow.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/postTextFieldParkingShow.imageset/uiViewTextfieldParkingShow@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/postTextFieldParkingShow.imageset/uiViewTextfieldParkingShow@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/uiViewSelectboxWarningSelect.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/uiViewSelectboxWarningSelect.imageset/uiViewSelectboxWarningSelect.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/uiViewSelectboxWarningSelect.imageset/uiViewSelectboxWarningSelect@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/uiViewSelectboxWarningSelect.imageset/uiViewSelectboxWarningSelect@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/uiViewSelectboxWarningUnselect.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/uiViewSelectboxWarningUnselect.imageset/uiViewSelectboxWarningUnselect.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/uiViewSelectboxWarningUnselect.imageset/uiViewSelectboxWarningUnselect@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/uiViewSelectboxWarningUnselect.imageset/uiViewSelectboxWarningUnselect@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/PostAttentionTVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/PostParkingTVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/PostTitleTVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/Extension+UITextFeild.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostAttentionTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostParkingTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Shared/PostCellTitleView.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/TabbarVC.swift
Labels: P0, 🍑hryeong🍑

#27 Feature/25 add font and color extension
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/Extension+UIColor.swift
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/Extension+UIFont.swift
Labels: P1, 🍑hryeong🍑

#41 [FEAT] 구경하기뷰 드라이브 코스, 테마 Cell 추가
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/selectbox_show.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/selectbox_show.imageset/selectbox_show.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/selectbox_show.imageset/selectbox_show@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/selectbox_show.imageset/selectbox_show@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/PostCourseThemeTVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostCourseThemeTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailVC.swift
  ChaRo-iOS/Podfile.lock
Labels: P0, 💖 InDong 💖

#44 🔨[FIX]: #37 - 스크롤할 때 테마 버튼이 추가로 생성되는 버그 해결
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostCourseThemeTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailVC.swift
Labels: bug, 💖 InDong 💖

#45 Feature/35 make detail view
  ChaRo-iOS/.Podfile.swp
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/BlueCheck.imageset/BlueCheck.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/BlueCheck.imageset/BlueCheck@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/BlueCheck.imageset/BlueCheck@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/BlueCheck.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icDown.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icDown.imageset/icDown.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icDown.imageset/icDown@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icDown.imageset/icDown@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/iconBack1.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/iconBack1.imageset/iconBack1.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/iconBack1.imageset/iconBack1@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/iconBack1.imageset/iconBack1@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/Home.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/HomePost.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/PostDetail.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/Tabbar.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/CommonCVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/HomePostDetailCVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/HomeThemeCVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/HomeTodayDriveTVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/HotDropDownTVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Support/SceneDelegate.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/CommonCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/HomePostDetailCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HotDropDownTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomePostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeVC.swift
  ChaRo-iOS/Podfile.lock
Labels: P0, 🍉 parkikbum 😝

#47 홈뷰랑 더보기 뷰 연결완료 및 잡코드 삭제
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/Home.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/HomePost.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/Tabbar.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/CommonCVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/HomeAreaRecommandTVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/HomeSeasonRecommandTVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/HomeSquareTVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/HomePostDetailCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeAreaRecommandTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeSeasonRecommandTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeSquareTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeThemeTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeTodayDriveTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomePostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/TabbarVC.swift
Labels: P0, enhancement, 🍉 parkikbum 😝

#53 Feature/43 make post detail map view
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/PostPathmapTCV.xib
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostCourseThemeTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostImagesTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostLocationTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostPathmapTCV.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostTitleTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailVC.swift
Labels: P0, 💖 InDong 💖

#55 [FEAT] 구경하기_테마 뷰 구현 #39
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/imagePlaceholder.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/imagePlaceholder.imageset/imagePlaceholder.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/imagePlaceholder.imageset/imagePlaceholder@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/imagePlaceholder.imageset/imagePlaceholder@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/Home.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/ThemePost.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/CommonCVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/HomeThemeCVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/ThemePostAllTVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/ThemePostDetailTVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/ThemePostThemeTVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/Extension+UIView.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/CommonCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/HomePostDetailCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/HomeThemeCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeAreaRecommandTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeSeasonRecommandTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeSquareTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeThemeTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeTodayDriveTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HotDropDownTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/ThemePostAllTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/ThemePostDetailTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/ThemePostThemeTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeNVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomePostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/ThemePostVC.swift
  ChaRo-iOS/Podfile.lock
Labels: P0, 🤍kingwonee🤍

#56 #49 일단 이름은 마이페이지인데 테이블뷰3개를 곁들인..
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/camera_mypage_wth_circle.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/camera_mypage_wth_circle.imageset/camera_mypage_wth_circle.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/camera_mypage_wth_circle.imageset/camera_mypage_wth_circle@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/camera_mypage_wth_circle.imageset/camera_mypage_wth_circle@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icHeartActive.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icHeartActive.imageset/icHeartActive.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icHeartActive.imageset/icHeartActive@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icHeartActive.imageset/icHeartActive@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icSave5Active.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icSave5Active.imageset/icSave5Active.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icSave5Active.imageset/icSave5Active@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icSave5Active.imageset/icSave5Active@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/save5_active.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/save5_active.imageset/save5_active.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/save5_active.imageset/save5_active@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/save5_active.imageset/save5_active@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/save5_inactive.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/save5_inactive.imageset/save5_inactive.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/save5_inactive.imageset/save5_inactive@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/save5_inactive.imageset/save5_inactive@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/setting2_white.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/setting2_white.imageset/setting2_white.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/setting2_white.imageset/setting2_white@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/setting2_white.imageset/setting2_white@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/write_active.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/write_active.imageset/write_active.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/write_active.imageset/write_active@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/write_active.imageset/write_active@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/write_inactive.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/write_inactive.imageset/write_inactive.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/write_inactive.imageset/write_inactive@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/write_inactive.imageset/write_inactive@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/HomePost.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/MyPage.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/HomePostDetailCVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/MyPagePostCVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/TabbarCVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/SearchKeywordCell.xib
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/HomePostDetailCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/MyPagePostCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/TabbarCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomePostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/MyPageVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/TabbarVC.swift
  ChaRo-iOS/Podfile
  ChaRo-iOS/Podfile.lock
Labels: P0, enhancement, 🍉 parkikbum 😝

#59 작성하기 뷰 초기 작업 완료, 타이틀 뷰 구현
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/close.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/close.imageset/close.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/close.imageset/close@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/close.imageset/close@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/Base.lproj/Main.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/CreatePost.storyboard
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/Extension+UIColor.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/TabbarVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/ViewController.swift
Labels: P0, enhancement, 💖 InDong 💖

#63 #58 사나이 박익범의 화려한 홈 화면 서버연동 ㅋ.ㅋ
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/HomePost.storyboard
  ChaRo-iOS/ChaRo-iOS/Source/Models/HomeDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/Contants.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/HomeDataService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/NetworkResult.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/CommonCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/HomeAnimationCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeAnimationTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeAreaRecommandTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeSeasonRecommandTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeSquareTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeTodayDriveTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/TabbarVC.swift
  ChaRo-iOS/Podfile
  ChaRo-iOS/Podfile.lock
Labels: P0, documentation, enhancement, 🍉 parkikbum 😝

#68 tag형이었던 배열 string배열로 바꾸었슴니당
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/CommonCVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/HomeAreaRecommandTVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/HomeSeasonRecommandTVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/HomeSquareTVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Models/HomeDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/CommonCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeAreaRecommandTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeSeasonRecommandTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeSquareTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeTodayDriveTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeVC.swift
Labels: 🍉 parkikbum 😝

#69 [FEAT] 테마 Cell 서버 연동 & 홈 Cell 데이터 전달 #57
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/heart_active.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/heart_active.imageset/heart_active.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/heart_active.imageset/heart_active@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/heart_active.imageset/heart_active@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Info.plist
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/CommonCVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Models/ThemeDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/GetThemeDataService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/CommonCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/HomeThemeCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeAreaRecommandTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeSeasonRecommandTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeSquareTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeThemeTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeTodayDriveTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/ThemePostAllTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/ThemePostDetailTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/ThemePostThemeTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/ThemePostVC.swift
  ChaRo-iOS/Podfile.lock
Labels: P0, 🤍kingwonee🤍

#74 Feature/62 connect server in path mapview
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icMapEnd.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icMapEnd.imageset/icEnd.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icMapEnd.imageset/icEnd@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icMapEnd.imageset/icEnd@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icMapStart.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icMapStart.imageset/icStart.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icMapStart.imageset/icStart@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icMapStart.imageset/icStart@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icMapWaypoint.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icMapWaypoint.imageset/icWaypoint.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icMapWaypoint.imageset/icWaypoint@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icMapWaypoint.imageset/icWaypoint@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icRouteEnd.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icRouteEnd.imageset/icRouteEnd.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icRouteEnd.imageset/icRouteEnd@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icRouteEnd.imageset/icRouteEnd@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icRouteStart.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icRouteStart.imageset/icRouteStart.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icRouteStart.imageset/icRouteStart@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icRouteStart.imageset/icRouteStart@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icRouteWaypoint.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icRouteWaypoint.imageset/icRouteWaypoint.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icRouteWaypoint.imageset/icRouteWaypoint@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icRouteWaypoint.imageset/icRouteWaypoint@3x.png
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/Extension+Date.swift
  ChaRo-iOS/ChaRo-iOS/Source/Models/AddressDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Models/SearchKeywordDataMadel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/Contants.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/MapService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/SearchKeywordService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/AddressButtonCell.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/SearchKeywordCell.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/AddressConfirmVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/AddressMainVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SearchKeywordVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SearchResultVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/TabbarVC.swift
  ChaRo-iOS/Podfile
  ChaRo-iOS/Podfile.lock
Labels: P0, 🍑hryeong🍑

#72 [FEAT] 하트 정보 POST
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/CommonCVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Models/LikeDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/Contants.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/GetThemeDataService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/LikeService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/CommonCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/ThemePostThemeTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/ThemePostVC.swift
Labels: P0, 🤍kingwonee🤍

#75 더보기 뷰 서버연동 및 더보기 인기순 최신순 구현
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/HomeTodayDriveTVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Models/DetailModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/Contants.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/DatailDataService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/NewDetailDataService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/CommonCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/HomePostDetailCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeTodayDriveTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomePostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeVC.swift
Labels: P0, 🍉 parkikbum 😝

#76 Feature/66 make onboarding
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/onboardingBackground1.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/onboardingBackground1.imageset/onboardingBackground1.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/onboardingBackground1.imageset/onboardingBackground1@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/onboardingBackground1.imageset/onboardingBackground1@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/onboardingBackground2.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/onboardingBackground2.imageset/onboardingBackground2.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/onboardingBackground2.imageset/onboardingBackground2@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/onboardingBackground2.imageset/onboardingBackground2@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/onboardingBackground3.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/onboardingBackground3.imageset/onboardingBackground3.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/onboardingBackground3.imageset/onboardingBackground3@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/onboardingBackground3.imageset/onboardingBackground3@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/OnBoard.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/OnBoardCVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/Extension+UIColor.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/OnBoardCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/AddressButtonCell.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/AddressMainVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/OnBoardVC.swift
Labels: P0, 🍑hryeong🍑

#81 Feature/60 create post title photo
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/imgDelete36px.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/imgDelete36px.imageset/img_delete_36px_black.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/imgDelete36px.imageset/img_delete_36px_black@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/imgDelete36px.imageset/img_delete_36px_black@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/plus.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/plus.imageset/plus.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/plus.imageset/plus@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/plus.imageset/plus@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/writeEmptyImage.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/writeEmptyImage.imageset/write_image.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/writeEmptyImage.imageset/write_image@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/writeEmptyImage.imageset/write_image@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/Base.lproj/LaunchScreen.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/CreatePostPhotosCVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/CreatePostPhotoTVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/CreatePostTitleTVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/Extension+UITextView.swift
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/Notification.Name.swift
  ChaRo-iOS/ChaRo-iOS/Source/Models/CreatePostDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/Contants.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/CreatePostService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/CreatePostPhotosCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostPhotoTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostTitleTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostPathmapTCV.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/TabbarVC.swift
  ChaRo-iOS/Podfile.lock
Labels: P0, enhancement, 💖 InDong 💖

#82 🔨[FIX]: #60 - Add photo function 추가
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostVC.swift
Labels: bug, 💖 InDong 💖

#83 Feature/78 post result connect server
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Source/Services/Contants.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/PostResultService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SearchPostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SearchResultVC.swift
Labels: P0, 🍑hryeong🍑

#85 [FEAT] 홈 서버 연동 리팩토링
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/cityView.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/cityView.imageset/image 115.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/cityView.imageset/image 115@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/cityView.imageset/image 115@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/nightView.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/nightView.imageset/image 116.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/nightView.imageset/image 116@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/nightView.imageset/image 116@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/HomeTodayDriveTVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Models/HomeDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/Contants.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/GetThemeDataService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/HomeAnimationCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeAnimationTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeAreaRecommandTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeSeasonRecommandTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeSquareTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeThemeTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeTodayDriveTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/ThemePostThemeTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/ThemePostVC.swift
  ChaRo-iOS/Podfile.lock
Labels: P0, 🤍kingwonee🤍

#89 Feature/78 post result collection view and header로 변경
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/PostResultHeaderCVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/Extension+UIColor.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/PostResultHeaderCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SearchResultVC.swift
  ChaRo-iOS/Podfile.lock
Labels: P0, 🍑hryeong🍑

#93 알림 뷰 구현zz
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/notificationImage.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/notificationImage.imageset/notificationImage.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/notificationImage.imageset/notificationImage@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/notificationImage.imageset/notificationImage@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/Home.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/MyPage.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/Notification.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/SearchResult.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/CommonCVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/MyPagePostCVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Models/MyPageDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/Contants.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/MyPageDataService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/CommonCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/HomePostDetailCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/MyPagePostCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomePostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/MyPageVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/NotificationVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SearchResultVC.swift
Labels: P0, documentation, 🍉 parkikbum 😝

#95 [FEAT] 로그인 구현 #86
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/Mask Group.imageset/Mask Group.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/Mask Group.imageset/Mask Group@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/Mask Group.imageset/Mask Group@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/idBackgroud.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/idBackgroud.imageset/login_id.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/idBackgroud.imageset/login_id@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/idBackgroud.imageset/login_id@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/maskGroup.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/maskGroup.imageset/maskGroup.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/maskGroup.imageset/maskGroup@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/maskGroup.imageset/maskGroup@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/pwdBackground.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/pwdBackground.imageset/login_password.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/pwdBackground.imageset/login_password@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/pwdBackground.imageset/login_password@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/Login.storyboard
  ChaRo-iOS/ChaRo-iOS/Source/Models/LoginDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Models/UserInfo.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/Contants.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/LoginService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeAreaRecommandTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeSeasonRecommandTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeSquareTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HotDropDownTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/ThemePostAllTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/LoginVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/ThemePostVC.swift
  ChaRo-iOS/Podfile.lock
Labels: P0, 🤍kingwonee🤍

#100 Feature/70 create post course theme
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/Extension+UIViewController.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostThemeTVC.swift
Labels: bug, enhancement, 💖 InDong 💖

#103 [FEAT] 게시물 작성한 내용 다음 VC로 데이터를 전달하기 위한 작업
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/Notification.Name.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostCourseTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostParkingWarningTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostPhotoTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostThemeTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostTitleTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostDriveCourseTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostVC.swift
  ChaRo-iOS/Podfile.lock
Labels: enhancement, 💖 InDong 💖

#104 🗿푸,,풀리,,풀리,,퀘,,풀리,,퀘,,풀리,,퀘
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/HomePost.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/MyPage.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/SearchResult.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/ThemePost.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/HotDropDownTVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Services/Contants.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/SavePostService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomePostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/MyPageVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SearchResultVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/ThemePostVC.swift
Labels: 🍉 parkikbum 😝

#108 Feature/102 add alert view
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/CommonCVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/ThemePostAllTVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/Extension+UIViewController.swift
  ChaRo-iOS/ChaRo-iOS/Source/Models/LoginDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/LoginService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/SearchKeywordService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/CommonCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostCourseThemeTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostDriveCourseTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostImagesTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostLocationTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostPathMapTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/AddressMainVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/LoginVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/MyPageVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/OnBoardVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SearchKeywordVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/TabbarVC.swift
Labels: P0, 🍑hryeong🍑

#109 Fix/106 change common cvc
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Source/Models/CreatePostDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/AddressMainVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/TabbarVC.swift
  ChaRo-iOS/Podfile.lock
Labels: P0, 🍑hryeong🍑

#111 [BUG] 디자인 QA 수정
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/Home.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/HomePost.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/ThemePost.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/HomeAreaRecommandTVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/HomeSeasonRecommandTVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/HomeSquareTVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/Extension+UICollectionView.swift
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/Extension+UIScreen.swift
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/Extension+UIViewController.swift
  ChaRo-iOS/ChaRo-iOS/Source/Models/LoginDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/LoginService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/CommonCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/HomeThemeCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeAreaRecommandTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeThemeTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeTodayDriveTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/ThemePostAllTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/ThemePostThemeTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomePostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/LoginVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/ThemePostVC.swift
  ChaRo-iOS/Podfile.lock
Labels: P1, bug, 🤍kingwonee🤍

#110 키보드와 레이아웃 오류를 해결했습니다.
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/Notification.Name.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostCourseTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostParkingWarningTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostThemeTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostTitleTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostVC.swift
  ChaRo-iOS/Podfile.lock
Labels: P1, bug, 💖 InDong 💖

#112 mypage 디자인 qa 완료~!
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/MyPage.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/MyPagePostCVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/HomeTodayDriveTVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/CommonCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/MyPagePostCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomePostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/MyPageVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SearchResultVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/TabbarVC.swift
  ChaRo-iOS/Podfile.lock
Labels: P0, 🍉 parkikbum 😝

#114 [BUGS] 디자인 QA
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/Login.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/CommonCVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/CommonCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeAreaRecommandTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeSeasonRecommandTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeSquareTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/ThemePostDetailTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/LoginVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/ThemePostVC.swift
Labels: P1, bug, 🤍kingwonee🤍

#116 🚑️[HOTFIX]: #115 - 알림 뷰 네비게이션 바 그림자
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/NotificationVC.swift
Labels: P0, 🍉 parkikbum 😝

#121 Hotfix/120 heyryeong qa
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/parkingNoImage.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/parkingNoImage.imageset/frame153.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/parkingNoImage.imageset/frame153@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/parkingNoImage.imageset/frame153@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/parkingYesImage.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/parkingYesImage.imageset/frame152.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/parkingYesImage.imageset/frame152@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/parkingYesImage.imageset/frame152@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/save_active.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/save_active.imageset/save5_active.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/save_active.imageset/save5_active@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/save_active.imageset/save5_active@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/save_inactive.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/save_inactive.imageset/save5_inactive.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/save_inactive.imageset/save5_inactive@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/save_inactive.imageset/save5_inactive@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/uiViewSelectboxParkingNo.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/uiViewSelectboxParkingNo.imageset/uiViewSelectboxNo.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/uiViewSelectboxParkingNo.imageset/uiViewSelectboxNo@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/uiViewSelectboxParkingNo.imageset/uiViewSelectboxNo@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/uiViewSelectboxParkingYes.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/uiViewSelectboxParkingYes.imageset/uiViewSelectboxYes.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/uiViewSelectboxParkingYes.imageset/uiViewSelectboxYes@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/uiViewSelectboxParkingYes.imageset/uiViewSelectboxYes@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/uiViewSelectboxYes.imageset/uiViewSelectboxYes.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/uiViewSelectboxYes.imageset/uiViewSelectboxYes@3x.png
  ChaRo-iOS/ChaRo-iOS/Source/Services/Contants.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/SavePostService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/CommonCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostAttentionTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostCourseThemeTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostDriveCourseTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostParkingTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SearchPostVC.swift
  ChaRo-iOS/Podfile.lock
Labels: P0, 🍑hryeong🍑

#122 작성하기에 급한 버그들을 수정했습니다.
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Source/Services/CreatePostService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostImagesTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailVC.swift
Labels: bug, 💖 InDong 💖

#123 [FEAT] 디자인 QA 반영 수정
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/CommonCVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/MyPagePostCVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/HomeThemeTVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/CollectionViewFooter.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/CommonCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/EmptyCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/EmptyCVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/MyPagePostCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/MyPageVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/TabbarVC.swift
Labels: P0, bug, 🤍kingwonee🤍

#124 속보) 박익범 킹피셔 씹어먹음 ㅋㅋ
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/CommonCVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/HomeAnimationCVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/loading.json
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/CommonCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/HomeAnimationCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeAreaRecommandTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomePostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/MyPageVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailVC.swift
Labels: 🍉 parkikbum 😝

#125 Bug/98 photopicker fix
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/PostTitleTVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostPhotoTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostVC.swift
  ChaRo-iOS/Podfile.lock
Labels: bug, 💖 InDong 💖
