Repository TeamChaRo/ChaRo-iOS, pull requests merged in 2022-05, with the labels that each got.

#218 [FEAT] #217 작성하기 화면 코드 최신화 및 리팩토링
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/CreatePostScene/WrittingScene/CreatePostPhotosCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/WrittingSence/CreatePostCourseTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/WrittingSence/CreatePostDriveCourseTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/WrittingSence/CreatePostParkingWarningTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/WrittingSence/CreatePostPhotoTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/WrittingSence/CreatePostThemeTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/WrittingSence/CreatePostTitleTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/WrittingScene/CreatePostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostSearchScene/SearchResultVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/Tabbar/TabbarVC.swift
Labels: 💖 InDong 💖, Refactor🔨

#216 [HOTFIX] #209 merge 에서 꼬인 부분 해결
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icId.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icId.imageset/id_40px.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icId.imageset/id_40px@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icId.imageset/id_40px@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icPassword.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icPassword.imageset/password_40px.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icPassword.imageset/password_40px@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icPassword.imageset/password_40px@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/idBackgroud.imageset/login_id.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/idBackgroud.imageset/login_id@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/idBackgroud.imageset/login_id@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/pwdBackground.imageset/login_password.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/pwdBackground.imageset/login_password@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/pwdBackground.imageset/login_password@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Literals/ImageLiterals.swift
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/SettingScene/Setting.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/SignScene/Login.storyboard
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/String+.swift
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/UIColor+.swift
  ChaRo-iOS/ChaRo-iOS/Source/Models/LoginJoinResponseDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Models/ThemeDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/Contants.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/EmailJoinService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/GetThemeDataService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/SocialJoinService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/SocialLoginService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/UpdatePasswordService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/UpdateProfileService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/UserDefaultKey.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/ThemeScene/ThemePostAllTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Shared/Component/PasswordView.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SettingScene/ChangeImageVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SettingScene/ChangePasswordVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SettingScene/SettingVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SignScene/FindPasswordVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SignScene/JoinVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SignScene/LoginVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SignScene/SNSLoginVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SignScene/Views/JoinContractView.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SignScene/Views/JoinProfileView.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/Tabbar/TabbarVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/ThemeScene/ThemePostVC.swift
Labels: 🍑hryeong🍑, Refactor🔨

#213 [FEAT] 마이페이지 설정 > 고객센터, 약관 기능 구현
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/SettingScene/SettingTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SettingScene/SettingVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/Tabbar/TabbarVC.swift
Labels: enhancement, P2, 💜 jingni 💜, 마이페이지뷰
