Repository TeamChaRo/ChaRo-iOS, pull requests merged in 2022-08, with the labels that each got.

#292 [FIX] 게시물 상세보기 - 좋아요, 스크랩 서버 연결 및 뷰 수정
  ChaRo-iOS/ChaRo-iOS/Source/Services/LikeService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/SavePostService.swift
  ChaRo-iOS/ChaRo-iOS/Source/ViewModels/PostDetailViewModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailScene/Component/PostDetailBottomView.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailScene/PostDetailVC.swift
Labels: P0, 🍑hryeong🍑, 상세보기뷰

#296 [FEAT] 둘러보기 시 접근 제한 기능 구현
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/UIViewController+.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/WrittingScene/CreatePostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeScene/HomeVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/MyPageScene/MyPageVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SettingScene/SettingVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/ThemeScene/ThemePostVC.swift
Labels: P0, 💜 jingni 💜, 홈뷰(둘러보기)

#297 작성하기 서버통신, 이미지 접근 권한 추가
  ChaRo-iOS/ChaRo-iOS/Resource/Info.plist
  ChaRo-iOS/ChaRo-iOS/Source/Models/AddressDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Models/CreatePostDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/Contants.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/CreatePostService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/UserDefaultKey.swift
  ChaRo-iOS/ChaRo-iOS/Source/ViewModels/AddressMainViewModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/AddressMainVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/WrittingScene/CreatePostVC.swift
Labels: P0

#298 Feature/290 second qa
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS.xcworkspace/contents.xcworkspacedata
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/BackIconWhite.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Literals/ImageLiterals.swift
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/HomeScene/Home.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/CommonCVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/HomeScene/HomeThemeTVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/HomeScene/HomeTodayDriveTVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/UILabel+.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/CommonCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeScene/HomeThemeTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeScene/HomeTodayDriveTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/CustomCollectionViewFlowLayout.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/FollowScene/FollowFollwingVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeScene/HomePostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeScene/HomeVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/MyPageScene/MyPageVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/MyPageScene/OtherMyPageVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostSearchScene/SearchResultVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/Tabbar/TabbarVC.swift
Labels: 🍉 parkikbum 😝

#302 [FEAT] 탭바 tintColor 컬러값 QA 반영
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/Tabbar/TabbarVC.swift
Labels: P0, 💜 jingni 💜
