Repository TeamChaRo/ChaRo-iOS, pull requests merged in 2022-06, with the labels that each got.

#215 [REFACTOR] 작성하기 - 지도 최근 검색기록 리펙토링
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/UINavigationController+.swift
  ChaRo-iOS/ChaRo-iOS/Source/Models/AddressDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Models/SearchKeywordDataMadel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/Contants.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/PostResultService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/SearchKeywordService.swift
  ChaRo-iOS/ChaRo-iOS/Source/ViewModels/AddressMainViewModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/ViewModels/SearchKeywordViewModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/MapScene/SearchKeywordCell.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/AddressConfirmVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/AddressMainVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/SearchAddressKeywordVC.swift
Labels: P0, 🍑hryeong🍑, Refactor🔨, Review Required☀️, 작성하기뷰-지도

#221 [FEAT] #220 작성하기 글 화면에 예외케이스 반영 및 개선
  ChaRo-iOS/ChaRo-iOS/Source/Models/FilterDatas.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/WrittingSence/CreatePostCourseTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/WrittingSence/CreatePostThemeTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/WrittingSence/CreatePostTitleTVC.swift
Labels: enhancement, 💖 InDong 💖, 작성하기뷰-글

#230 [FIX] 서버 base URL 변경
  ChaRo-iOS/ChaRo-iOS/Source/Services/Contants.swift
Labels: P0, 🍑hryeong🍑

#223 [FEAT] #222 비밀번호 찾기 서버 구현
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Source/Services/Contants.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/FindPasswordService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SignScene/FindPasswordVC.swift
Labels: enhancement, P0

#236 [FEAT] 구경하기 이미지 클릭 시 확대 화면으로 전환
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS.xcworkspace/appleLogo.svg
  ChaRo-iOS/ChaRo-iOS/Source/ViewModels/ExpendedImageViewModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostDetailScene/PostPhotoCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostDetailScene/PostPhotoTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailScene/ExpendedImageVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailScene/PostDetailVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SignScene/LoginVC.swift
  ChaRo-iOS/Podfile.lock
Labels: P0, 🍑hryeong🍑, 상세보기뷰

#238 [FEAT] 푸시알림 조회/읽음 기능 구현
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icAlarmActive.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icAlarmActive.imageset/alarmActive_44px.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icAlarmActive.imageset/alarmActive_44px@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icAlarmActive.imageset/alarmActive_44px@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Literals/ImageLiterals.swift
  ChaRo-iOS/ChaRo-iOS/Source/Models/NotificationListModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/Contants.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/NotificationService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/NotificationTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/NotificationVC.swift
Labels: enhancement, P0, 💜 jingni 💜, 알림뷰

#240 [FEAT] 안읽은 알림이 있을 때 홈화면의 알림 아이콘 활성화
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icAlarmActiveWhite.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icAlarmActiveWhite.imageset/alarm_active_white.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icAlarmActiveWhite.imageset/alarm_active_white@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icAlarmActiveWhite.imageset/alarm_active_white@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Literals/ImageLiterals.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeScene/HomeVC.swift
Labels: enhancement, 💜 jingni 💜, 홈뷰(둘러보기)

#242 [FEAT] 좋아요 리스트에서 다른 사람 계정 누를 경우 → 타인 마이페이지로 이동
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Literals/ImageLiterals.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/FollowScene/FollowButton.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/FollowScene/FollowFollowingTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeScene/HomePostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeScene/HomeVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/MyPageScene/OtherMyPageVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailScene/PostDetailVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailScene/PostLikeListVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostSearchScene/SearchPostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/ThemeScene/ThemePostVC.swift
Labels: P0, 🍑hryeong🍑, 상세보기뷰, 마이페이지뷰

#251 [Feat] 작성하기 화면에서 이미지 추가, 삭제 로직을 개선합니다.
  ChaRo-iOS/ChaRo-iOS/Resource/Info.plist
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/Notification.Name.swift
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/UIColor+.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/CreatePostScene/WrittingScene/CreatePostPhotosCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/WrittingSence/CreatePostPhotoTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/WrittingScene/CreatePostVC.swift
Labels: enhancement, P0, 작성하기뷰-글

#253 [BUG] 홈 TableViewHeight 게시물 수에 맞게 유동적으로 줄어들도록 수정
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeScene/HomeVC.swift
Labels: P0, 💜 jingni 💜, Refactor🔨, 홈뷰(둘러보기)

#255 [FEAT] 구경하기 - 이미지 확대 및 현재 보던 index부터 볼 수 있게 데이터 전달
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostDetailScene/PostPhotoCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostDetailScene/PostPhotoTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailScene/ExpendedImageVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailScene/PostDetailVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/ThemeScene/ThemePostVC.swift
Labels: enhancement, P2, 🍑hryeong🍑, 상세보기뷰

#256 [REFACTOR] 설정뷰 코드 리펙토링
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Source/Models/SettingDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Models/SettingViewDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/SettingScene/SettingTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SettingScene/NoticeVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SettingScene/SettingVC.swift
Labels: P2, 💜 jingni 💜, Refactor🔨, 마이페이지뷰

#257 [Bug] 작성하기 사진 높이 잘리는 문제 해결 & 작성하기 서버 통신에 필요한 재모델링
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Source/Models/CreatePostDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Models/WarningType.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/Contants.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/CreatePostService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/WrittingSence/CreatePostParkingWarningTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/WrittingScene/CreatePostVC.swift
Labels: bug🐞, enhancement, P0, 💖 InDong 💖

#258 [FIX] 마이페이지 오류 수정
  ChaRo-iOS/ChaRo-iOS/Source/Models/SettingDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/Contants.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/FollowCheckService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/GetFollowDataService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/UserDefaultKey.swift
  ChaRo-iOS/ChaRo-iOS/Source/ViewModels/AddressMainViewModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/FollowScene/FollowFollwingVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/MyPageScene/MyPageVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/MyPageScene/OtherMyPageVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailScene/PostDetailVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SignScene/LoginVC.swift
Labels: bug🐞, P0, 🍉 parkikbum 😝
