Repository TeamChaRo/ChaRo-iOS, pull requests merged in 2022-07, with the labels that each got.

#262 [FEAT] 알림창 EmptyView 구현
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icAlarmEmptyGraphic.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icAlarmEmptyGraphic.imageset/alarm_empty_graphic.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icAlarmEmptyGraphic.imageset/alarm_empty_graphic@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icAlarmEmptyGraphic.imageset/alarm_empty_graphic@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Literals/ImageLiterals.swift
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/Notification.storyboard
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/UIColor+.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/NotificationTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/NotificationVC.swift
Labels: P0, 💜 jingni 💜, 알림뷰

#266 ✅ [CHORE] 설정뷰 URL 링크 변경
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SettingScene/SettingVC.swift
Labels: P0, 💜 jingni 💜, 마이페이지뷰

#268 [BUG] 설정 뷰에서 프로필수정, 비밀번호 수정뷰 화면전환시 백그라운드 컬러 투명인 버그 수정
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SettingScene/SettingVC.swift
Labels: bug🐞, 💜 jingni 💜, 마이페이지뷰

#271 [CHORE] 공지사항뷰 - 공지사항 펼쳤을 때 화살표도 같이 펼쳐지도록 UI 수정
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icNoticeOpen.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icNoticeOpen.imageset/icNoticeOpen.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icNoticeOpen.imageset/icNoticeOpen@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icNoticeOpen.imageset/icNoticeOpen@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Literals/ImageLiterals.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/SettingScene/NoticeTitleTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SettingScene/NoticeVC.swift
Labels: P0, 💜 jingni 💜, 마이페이지뷰

#273 [FIX] 작성하기 글 QA 수정
  ChaRo-iOS/ChaRo-iOS/Resource/Literals/ImageLiterals.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/CreatePostService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/CreatePostScene/WrittingScene/CreatePostPhotosCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/WrittingSence/CreatePostCourseTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/WrittingSence/CreatePostDriveCourseTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/WrittingSence/CreatePostParkingWarningTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/WrittingSence/CreatePostThemeTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/WrittingScene/CreatePostVC.swift
Labels: bug🐞, P1, 작성하기뷰-글

#279 [FIX] Banner 관련된 UI 수정
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/BannerScene/Cell/BannerAboutCell.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/BannerScene/FourthBannerVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/BannerScene/ThirdBannerVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeScene/HomeVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailScene/PostDetailVC.swift
Labels: bug🐞, P0, 🍑hryeong🍑, 배너뷰

#283 [FIX] 게시물 상세보기 수정 및 게시물 찾기 뷰 UI 수정
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icBigHeartActive.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icBigHeartActive.imageset/icBigHeartActive.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icBigHeartActive.imageset/icBigHeartActive@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icBigHeartActive.imageset/icBigHeartActive@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icBigHeartInactive.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icBigHeartInactive.imageset/icBigHeartInactive.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icBigHeartInactive.imageset/icBigHeartInactive@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icBigHeartInactive.imageset/icBigHeartInactive@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icBigSaveActive.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icBigSaveActive.imageset/icBigSaveActive.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icBigSaveActive.imageset/icBigSaveActive@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icBigSaveActive.imageset/icBigSaveActive@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icBigSaveInactive.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icBigSaveInactive.imageset/icBigSaveInactive.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icBigSaveInactive.imageset/icBigSaveInactive@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icBigSaveInactive.imageset/icBigSaveInactive@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Literals/ImageLiterals.swift
  ChaRo-iOS/ChaRo-iOS/Source/ViewModels/PostDetailViewModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/PostDetailScene/PostLocationTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeScene/HomeVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailScene/Component/PostDetailBottomView.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailScene/ExpendedImageVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailScene/ExpendedMapVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailScene/PostDetailVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailScene/PostLikeListVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostSearchScene/SearchPostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostSearchScene/SearchResultVC.swift
Labels: bug🐞, P0, 🍑hryeong🍑, 상세보기뷰, 검색하기뷰

#286 [CHORE] 검색하기 관련 UI 수정
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/PostSearchScene/SearchPost.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/PostSearchScene/SearchResult.storyboard
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeScene/HomeVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailScene/PostDetailVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostSearchScene/SearchPostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostSearchScene/SearchResultVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SignScene/LoginVC.swift
Labels: bug🐞, P0, 🍑hryeong🍑, 검색하기뷰, 검색하기결과뷰

#287 [FIX] 구경하기 서버 호출 변경된 데이터 적용
  ChaRo-iOS/ChaRo-iOS/Source/Models/PostDetailDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/PostResultService.swift
  ChaRo-iOS/ChaRo-iOS/Source/ViewModels/PostDetailViewModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeScene/HomeAreaRecommandTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeScene/HomeSeasonRecommandTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeScene/HomeSquareTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HomeScene/HomeTodayDriveTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/ThemeScene/ThemePostAllTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/BannerScene/BannerVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/BannerScene/ThirdBannerVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeScene/HomePostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeScene/HomeVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/MyPageScene/MyPageVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/MyPageScene/OtherMyPageVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/NotificationVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailScene/PostDetailVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostSearchScene/SearchResultVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/ThemeScene/ThemePostVC.swift
Labels: bug🐞, P0, 🍑hryeong🍑, 홈뷰(둘러보기), 상세보기뷰, 검색하기결과뷰

#289 [FIX] 베너 이미지 변경 및 구경하기 지도 확대뷰 수정
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/imgHomeBannerAboutCharo.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/imgHomeBannerAboutCharo.imageset/imgHomeBannerAboutCharo.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/imgHomeBannerAboutCharo.imageset/imgHomeBannerAboutCharo@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/imgHomeBannerAboutCharo.imageset/imgHomeBannerAboutCharo@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/imgHomeBannerCarTheater.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/imgHomeBannerCarTheater.imageset/imgHomeBannerCarTheater.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/imgHomeBannerCarTheater.imageset/imgHomeBannerCarTheater@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/imgHomeBannerCarTheater.imageset/imgHomeBannerCarTheater@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/imgHomeBannerGangneung.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/imgHomeBannerGangneung.imageset/imgHomeBannerGangneung.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/imgHomeBannerGangneung.imageset/imgHomeBannerGangneung@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/imgHomeBannerGangneung.imageset/imgHomeBannerGangneung@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/imgHomeBannerPlaylist.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/imgHomeBannerPlaylist.imageset/imgHomeBannerPlaylist.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/imgHomeBannerPlaylist.imageset/imgHomeBannerPlaylist@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/imgHomeBannerPlaylist.imageset/imgHomeBannerPlaylist@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/imgPlaylistBanner.imageset/imgPlaylistBanner.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/imgPlaylistBanner.imageset/imgPlaylistBanner@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/imgPlaylistBanner.imageset/imgPlaylistBanner@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Literals/ImageLiterals.swift
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/UIScreen+.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/BannerScene/BannerVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/BannerScene/Cell/PlayListTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/BannerScene/Component/SecondBannerHeaderView.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeScene/HomeVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailScene/ExpendedMapVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostSearchScene/SearchResultVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SignScene/LoginVC.swift
Labels: bug🐞, P0, 홈뷰(둘러보기), 배너뷰
