Repository TeamChaRo/ChaRo-iOS, pull requests merged in 2022-04, with the labels that each got.

#204 [FEAT] 작성하기 테마선택뷰 추가 기능 구현 완료
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/CreatePostScene/WrittingScene/CreatePost.storyboard
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/WrittingSence/CreatePostThemeTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/WrittingScene/CreatePostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/WrittingScene/PresentationController.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/WrittingScene/ThemePopupVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/WrittingScene/TransitionVC.swift
Labels: enhancement, P0, 💜 jingni 💜, 작성하기뷰-글

#206 [FEAT] 탭바 수정 및 마이페이지 버그 수정
  ChaRo-iOS/ChaRo-iOS/Resource/Literals/ImageLiterals.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/GetFollowDataService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/FollowScene/FollowFollowingTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/FollowScene/FollowFollwingVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeScene/HomeVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/MyPageScene/MyPageVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/MyPageScene/OtherMyPageVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailScene/PostLikeListVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/Tabbar/TabbarVC.swift
Labels: bug🐞, enhancement, P1, 🍉 parkikbum 😝, 마이페이지뷰

#211 [BUG] 홈 네비게이션에 차로 로고 안나오는 증상 수정 및 디자인 변경
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeScene/HomeVC.swift
Labels: bug🐞, P0, 🍉 parkikbum 😝, 홈뷰(둘러보기)
