Repository TeamChaRo/ChaRo-iOS, pull requests merged in 2022-03, with the labels that each got.

#175 [Feat]#163 비밀번호 찾기
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/SignScene/Login.storyboard
  ChaRo-iOS/ChaRo-iOS/Source/Models/LoginDataModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/EmailJoinService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/IsDuplicatedEmailService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/IsDuplicatedNicknameService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/LoginService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Shared/Component/JoinInputView.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SignScene/FindPasswordVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SignScene/LoginVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SignScene/Views/JoinContractView.swift
Labels: P0, 🤍kingwonee🤍, 로그인뷰

#185 [Feat] image literals 적용
  ChaRo-iOS/ChaRo-iOS/Resource/Literals/ImageLiterals.swift
Labels: enhancement, P1, 🍑hryeong🍑, Review Required☀️

#190 [FEAT] 게시물 좋아요 리스트 서버 연결 및 tableview 구성
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/FollowScene/FollowFollowingTVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Extensions/UITableView+.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/Contants.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/PostResultService.swift
  ChaRo-iOS/ChaRo-iOS/Source/ViewModels/PostLikeListViewModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/FollowScene/FollowFollowingTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/NewHotFilterView.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/FollowScene/FollowFollwingVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailScene/PostDetailVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailScene/PostLikeListVC.swift
Labels: P0, 🍑hryeong🍑, Review Required☀️, 상세보기뷰

#192 [FEAT] 작성하기 -지도뷰 첫 시작 안내 뷰 애니메이션 구현
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/mapFirstGuide.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/mapFirstGuide.imageset/Group 731.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/mapFirstGuide.imageset/Group 731@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/mapFirstGuide.imageset/Group 731@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Literals/ImageLiterals.swift
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/CreatePostScene/MapScene/AddressConfirm.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/CreatePostScene/MapScene/AddressMain.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/CreatePostScene/MapScene/SearchKeyword.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/CreatePostScene/MapScene/AddressButtonCell.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/CreatePostScene/MapScene/SearchKeywordCell.xib
  ChaRo-iOS/ChaRo-iOS/Source/ViewModels/PostLikeListViewModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/OnBoardScene/OnBoardCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/MapScene/AddressButtonCell.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/CreatePostScene/MapScene/SearchKeywordCell.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/Component/MapGuideView.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/AddressConfirmVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/AddressMainVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/SearchAddressKeywordVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/MapScene/SearchKeywordVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/CreatePostScene/WrittingScene/CreatePostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailScene/Component/PostDetailBottomView.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailScene/PostDetailVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostDetailScene/PostLikeListVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostSearchScene/SearchPostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostSearchScene/SearchResultVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/SplashScene/SplashVC.swift
Labels: P0, 🍑hryeong🍑, Review Required☀️, 작성하기뷰-지도

#194 [FEAT] 인기순/최신순 필터 교체
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icDown.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icDown.imageset/down_42px.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icDown.imageset/down_42px@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icDown.imageset/down_42px@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icDown.imageset/icDown.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icDown.imageset/icDown@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/icDown.imageset/icDown@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Literals/ImageLiterals.swift
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/HomeScene/HomePost.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/PostSearchScene/SearchResult.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/ThemeScene/ThemePost.storyboard
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/CVC/HomeScene/HomePostDetailCVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/HotDropDownTVC.xib
  ChaRo-iOS/ChaRo-iOS/Resource/Xibs/TVC/ThemeScene/ThemePostDetailTVC.xib
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/CVC/HomeScene/HomePostDetailCVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/HotDropDownTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/ThemeScene/ThemePostDetailTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/FilterCellView.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/FilterView.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/NewHotFilterView.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeScene/HomePostVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/MyPageScene/MyPageVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/MyPageScene/OtherMyPageVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/PostSearchScene/SearchResultVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/ThemeScene/ThemePostVC.swift
Labels: enhancement, P0, 🍉 parkikbum 😝, Review Required☀️, 마이페이지뷰

#199 [FEAT] 알림 목록뷰 UI 구성 및 서버 통신 구현
  ChaRo-iOS/ChaRo-iOS.xcodeproj/project.pbxproj
  ChaRo-iOS/ChaRo-iOS/Resource/Storyboards/Notification.storyboard
  ChaRo-iOS/ChaRo-iOS/Source/Models/NotificationListModel.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/Contants.swift
  ChaRo-iOS/ChaRo-iOS/Source/Services/NotificationService.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/NotificationTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/NotificationVC.swift
Labels: enhancement, P1, 💜 jingni 💜, 알림뷰

#198 [FEAT] 마이페이지 이미지 리터럴 추가 및 버튼 이미지 제거 후 이미지 없는 버튼으로 변경
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/FollowButtonGray.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/FollowButtonGray.imageset/FollowButtonImage.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/FollowButtonGray.imageset/FollowButtonImage@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/FollowButtonGray.imageset/FollowButtonImage@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/followButtonWhite.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/followButtonWhite.imageset/followButton.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/followButtonWhite.imageset/followButton@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/followButtonWhite.imageset/followButton@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/followingButton.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/followingButton.imageset/followingButton.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/followingButton.imageset/followingButton@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/followingButton.imageset/followingButton@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/followingButtonImage.imageset/Contents.json
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/followingButtonImage.imageset/followingButtonImage.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/followingButtonImage.imageset/followingButtonImage@2x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Assets.xcassets/followingButtonImage.imageset/followingButtonImage@3x.png
  ChaRo-iOS/ChaRo-iOS/Resource/Literals/ImageLiterals.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/Cells/TVC/FollowScene/FollowFollowingTVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/FilterView.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/FollowScene/FollowFollwingVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/HomeScene/HomeVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/MyPageScene/MyPageVC.swift
  ChaRo-iOS/ChaRo-iOS/Source/Views/VCs/MyPageScene/OtherMyPageVC.swift
Labels: P1, 🍉 parkikbum 😝, 마이페이지뷰
